---
title: "Evaluation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}
# libraries
library(tidyverse)
library(reshape2)
library(lubridate)
library(grid)
library(gridExtra)
library(covidcast)

# utils
source("utils/eval.r")
source("utils/delays.r")

# helper
source("helper/plotting.r")
```

## Data

```{r}
# files
files <- list.files("predictions", pattern = ".rds", full.names = T)

# phase labels
phase_labs <- read_csv("data/us-selected-states_labeled-phases.csv") %>%
  rename(start_date = date) %>%
  group_by(state) %>%
  arrange(start_date) %>%
  mutate(end_date = dplyr::lead(as.character(start_date), 1)) %>%
  ungroup() %>%
  mutate(end_date = ifelse(is.na(end_date), "2021-03-15", end_date)) %>%
  mutate(end_date = as.Date(end_date)) %>%
  mutate(epidemic_phase = factor(epidemic_phase, levels = c(c("exponential growth", "subexponential growth", "plateau", 
                                                              "subexponential decline", "exponential decline"))))

# models
models <- c("cori", "arima", "prophet", "gp")
model_names <- c("EpiEstim", "ARIMA", "Prophet", "GP")
names(model_names) <- models

# states
states <- c("az","ca","il","md","nj","ny")
state_names <- c("Arizona", "California", "Illinois", 
                 "Maryland", "New Jersey", "New York")
names(state_names) <- states

# parameters
# - model colors
mcols <- RColorBrewer::brewer.pal(length(models), "Dark2")
# - discretize forecast weeks
n_brks <- c(0, 7, 14, 21)
n_lbs <- c("1-week forecast", "2-weeks forecast", "3-weeks forecast")
# - discretize incidence
inc_small_brks <- c(-Inf, 10, 30, 50, 70, 90, 110, 150, Inf)
# - default ahead forecast to look at
n_ahead <- 10

# graphical parameters
max_inc <- 300
```


## Plot forecast

### Example forecast (California)

```{r}
df_ex <- read_files(files[2])
```

#### Single 3-week

```{r}
df_ex_single <- df_ex %>%
  dplyr::filter(forecast_date == "2020-11-21") %>%
  mat_to_list_rowwise() %>%
  unnest(cols = models) %>%
  mutate(state_id = "ca") %>%
  comp_inc(cori) %>%
  rename(target = incidence) %>%
  dplyr::select(date, target, models) %>%
  mutate_at(models, ~ ifelse(. > max_inc, max_inc, .)) %>%
  melt(c("date")) %>%
  mutate(variable = recode(variable, !!! model_names)) 

ex_single_pl <- df_ex_single %>%
 plot_predict(interval=T) + 
  labs(y = "Incidence (new cases per 100,000 population)", 
       color = "CrI", fill = "CrI") +
  scale_y_continuous(limits = c(0, max_inc), expand = c(0,0)) +
  scale_x_date(breaks = as.Date(c("2020-11-21", "2020-11-28", "2020-12-05", "2020-12-11")),
               date_labels = "%b %d", expand = c(0,0)) + 
  theme(panel.spacing = unit(2, "lines"))

ex_single_pl
```

#### Full 10-day 

```{r}
df_ex_full <- df_ex %>%
  get_n_ahead() %>%
  mat_to_list() %>%
  unnest(cols = models) %>%
  mutate(state_id = "ca") %>%
  comp_inc(cori) %>%
  rename(target = incidence) %>%
  dplyr::select(date, target, models) %>%
  mutate_at(models, ~ ifelse(. > max_inc, max_inc, .)) %>%
  melt(c("date")) %>%
  mutate(variable = recode(variable, !!! model_names)) 

ex_full_pl <- df_ex_full %>%
  plot_predict(interval = T) +
  scale_y_continuous(limits = c(0, max_inc), expand = c(0,0)) +
  labs(y = "Incidence (new cases per 100,000 population)", 
       color = "CrI", fill = "CrI") +
  theme(panel.spacing = unit(2, "lines"))

ex_full_pl

ex_full_pl_wtitle <- ex_full_pl +
  labs(title = "Probabilistic forecast for California", 
       subtitle = "Probabilistic 10-day forecast (blue) of incidence with COVID-19 (black) for California")

save_plot(ex_full_pl_wtitle, "results/prob_forecast_ca.png", w = 16, h = 16) 
save_plot(ex_full_pl, "results/prob_forecast_ca.pdf", w = 16, h = 12) 
```

```{r}
ex_pl <- grid.arrange(ex_single_pl + labs(title = "a"), 
                      ex_full_pl + theme(legend.position = "none") + labs(title = "b"),
                      ncol = 1, widths = 16, heights = c(9, 9))

save_plot(ex_pl, "results/examples.pdf", w = 16, h = 18)
```

### By model and country

```{r}
pdf(file = "results/ts_forecast.pdf", w = 21 / cm(1), h = 14 / cm(1))
for (f in files) {
  ctry <- gsub(".rds", "", basename(f))
  print(
    read_files(f) %>%
      get_n_ahead() %>%
      mat_to_list() %>%
      unnest(cols = models) %>%
      mutate(state_id = tolower(ctry)) %>%
      comp_inc(cori) %>%
      rename(target = incidence) %>%
      dplyr::select(date, target, models) %>%
      mutate_at(models, ~ ifelse(. > max_inc, max_inc, .)) %>%
      melt(c("date")) %>%
      plot_predict(interval = T) +
      scale_y_continuous(limits = c(0, max_inc), expand = c(0,0)) +
      labs(y = "Incidence (per 100,000 population)", 
           color = "CrI", fill = "CrI",
           title = ctry, 
           subtitle = paste0("Probabilistic ", n_ahead, "-day ahead forecast (blue) for daily new cases (black)")) 
  )
  
  print(
    read_files(f) %>%
      get_mean_forecast() %>%
      dplyr::filter(n %in% c(1, 7, 14, 21)) %>%
      mutate(n = factor(as.character(n), levels = c("1", "7", "14", "21"))) %>%
      mutate(state_id = tolower(ctry)) %>%
      comp_inc(cori) %>%
      rename(target = incidence) %>%
      dplyr::select(date, target, n, models) %>%
      mutate_at(models, ~ ifelse(. > max_inc, max_inc, .)) %>%
      reshape2::melt(c("date", "n")) %>%
      plot_predict(interval = F) +
      scale_y_continuous(limits = c(0, max_inc), expand = c(0,0)) +
      labs(y = "Incidence (per 100,000 population)",
           color = "Number of days forecasted ahead",
           title = ctry, 
           subtitle = "Posterior mean N-days ahead forecast (color) for daily new cases (black)")
  )
}
dev.off()
```


### Average-7d by country

```{r}
mean10 <- do.call(rbind, lapply(files, function(f) {
  read_files(f) %>%
    get_mean_forecast() %>%
    dplyr::filter(n == n_ahead) %>%
    mutate(state_id = tolower(gsub(".rds", "", basename(f)))) %>%
    comp_inc(cori) %>%
    rename(target = incidence, id = state_id) %>%
    dplyr::select(id, date, target, models) %>%
    melt(measure.vars = c("target", models)) %>%
    group_by(id, variable) %>%
    mutate(value = zoo::rollmean(value, k = 7, fill = NA, align = "right")) %>%
    ungroup() %>%
    na.omit()
}))

mean10_pl <- mean10 %>% mutate(value = ifelse(value > max_inc, max_inc, value)) %>%
  ggplot(mapping = aes(x = date, y = value, color = variable)) +
  facet_wrap(~ id, ncol = 3, scales = "free_x") +
  geom_line(alpha = .5) +
  scale_color_manual(values = c("black", mcols)) +
  scale_y_continuous(limits = c(0, max_inc), expand = c(0,0)) +
  scale_x_date(date_breaks = "1 month") +
  theme_bw2() +
  theme(axis.title.x = element_blank(), legend.position = "top",
        axis.text.x = element_text(angle = 90)) +
  labs(y = "Incidence (per 100,000 population)", 
       color = "Model forecast",
       title = "Mean forecast by model", 
       subtitle = paste0("Mean Probabilistic ", n_ahead, "-day ahead forecast (color) for daily new cases (dark)")) 

mean10_pl

save_plot(mean10_pl, "results/ts_mean10.png", w = 21, h = 21)
```



## Calibration, Sharpness, and Bias

### Proba. calibration

```{r}
df_pCalib <- do.call(rbind, map(files, function(f) {
  print(sprintf("Processing file %s", f))
  read_files(f) %>%
    add_n_ahead() %>%
    .$data %>%
    lapply(., function(X) mutate(X, state_id = tolower(gsub(".rds", "", basename(f))))) %>%
    lapply(., function(X) comp_inc(X, cori)) %>%
    lapply(., function(X) cbind(dplyr::select(X, state_id, date, n, incidence), 
                                sapply(models, function(m) pred_score(X[[m]], X$incidence, type = "calibration")))) %>%
    do.call(rbind, .)
}))

pCalib_pl <- df_pCalib %>%
  mutate(n = cut(n, breaks = n_brks, labels = n_lbs)) %>%
  dplyr::select(n, models) %>%
  reshape2::melt("n") %>%
  mutate(variable = recode(variable, !!! model_names)) %>%
  ggplot(aes(x = value, color = variable, fill = variable)) +
  facet_wrap(~ n, ncol = 3) +
  geom_density(alpha = 0.1) + # geom_histogram(aes(y = stat(count) / sum(count)))
  scale_y_continuous(expand = c(0,0), limits = c(0,3), breaks = c(1,2,3)) +
  scale_x_continuous(expand = c(0,0), breaks = seq(0,1,.2)) +
  scale_color_manual(values = mcols) +
  scale_fill_manual(values = mcols) +
  labs(x = "Probability integral transform", 
       y = "Density") +
  theme_bw2() +
  theme(legend.title = element_blank())

pCalib_pl

pCalib_pl_wtitle <- pCalib_pl +
  labs(title = "Probabilistic Calibration",
       subtitle = "PIT histogram by model and n-week forecast")

save_plot(pCalib_pl_wtitle, "results/calibration_probabilistic.png", w = 16, h = 8)
```


### Marginal calibration

```{r}
D <- A$data %>%
  lapply(., function(X) X %>% dplyr::select(date, incidence)) %>%
  do.call(rbind, .) %>%
  group_by(date) %>%
  slice(1) %>%
  ungroup()

B <- A %>% 
  add_n_ahead() %>%
  lapply(., function(X) comp_inc(X, cori)) %>%
  lapply(., function(X) cbind(dplyr::select(X, state_id, date, n, incidence), 
                                sapply(models, function(m) pred_score(X[[m]], X$incidence, type = "calibration"))))
  


  
  
    add_n_ahead() %>%
    .$data %>%
    lapply(., function(X) mutate(X, state_id = tolower(gsub(".rds", "", basename(f))))) %>%
    lapply(., function(X) comp_inc(X, cori)) %>%
  lapply(., function(x) sapply(models, function(m) ecdf))

Gx <- df_pCalib %>%
  group_by(state_id, date) %>% 
  slice(1) %>%
  ungroup() %>%
  group_by(state_id) %>%
  mutate(Gx = ecdf(incidence)(incidence)) %>%
  ungroup() %>%
  dplyr::select(state_id, date, Gx)

df_mCalib <- df_pCalib %>%
  left_join(Gx) %>%
  mutate_at(vars(models), ~ . - Gx) %>%
  mutate(incidence = as.numeric(as.character(cut(incidence, breaks = inc_small_brks, labels = inc_small_brks[-1])))) %>%
  dplyr::select(n, incidence, models) %>%
  mutate(n = cut(n, breaks = n_brks, labels = n_lbs)) %>%
  reshape2::melt(c("n", "incidence")) %>%
  group_by(n, incidence, variable) %>%
  summarize(value = mean(value)) %>%
  ungroup() 

inc_small_brks_pl <- inc_small_brks
inc_small_brks_pl[1] <- 0
inc_small_brks_pl[length(inc_small_brks_pl)] <- 170
mCalib_pl <- df_mCalib %>%
  mutate(variable = recode(variable, !!! model_names)) %>%
  mutate(incidence = ifelse(is.infinite(incidence), 170, incidence)) %>%
  ggplot(aes(x = incidence, y = value, color = variable)) +
  geom_line() +
  geom_point(shape = 1) +
  facet_wrap(~ n, ncol = 3) +
  geom_hline(aes(yintercept = 0), linetype = "dotted") +
  scale_x_continuous(breaks = inc_small_brks_pl, limits = c(0, 180), expand = c(0,0)) +
  scale_y_continuous(limits = c(-.6, .6), breaks = seq(-0.6,0.6,.3)) +
  scale_color_manual(values = mcols) +
  labs(x = "Incidence (new cases per 100,000 people)", 
       y = expression(bar(CDF)[Forecast]-CDF[Observed])) +
  theme_bw2() +
  theme(legend.title = element_blank()) 

mCalib_pl

mCalib_pl_wtitle <- mCalib_pl +
  labs(title = "Marginal Calibration",
       subtitle = "Difference between average predictive and empirical CDF by method and n-week forecast")

save_plot(mCalib_pl_wtitle, "results/calibration_marginal.png", w = 16, h = 8)
```


### Sharpness

```{r}
qq <- 0.05
qq_name <- "90"
df_sharp <- do.call(rbind, map(files, function(f) {
  print(sprintf("Processing file %s", f))
  read_files(f) %>% add_pred_score(f, models = models, type = "sharpness", q = qq)
}))

sharp_pl <- df_sharp %>%
  dplyr::select(n, models) %>%
  melt("n") %>%
  group_by(n, variable) %>%
  summarize(value = median(value)) %>%
  ungroup() %>%
  mutate(variable = recode(variable, !!! model_names)) %>%
  ggplot(aes(x = n, y = value, color = variable)) +
  geom_line() +
  geom_point(shape = 1) +
  scale_x_continuous(minor_breaks = seq(0,21,1), expand = c(0,0), breaks = c(1,7,14,21), limits = c(0.5,21.5)) +
  scale_y_continuous(expand = c(0,0), limits = c(0, 50)) +
  scale_color_manual(values = mcols) +
  labs(x = "Number of days forecasted ahead", 
       y = paste0("Median size of ", qq_name, "%-CrI (incidence)")) +
  theme_bw2() +
  theme(legend.title = element_blank())

sharp_pl

sharp_pl_wtitle <- sharp_pl +
  labs(title = "Sharpness",
       subtitle = paste0("Median size of ", qq_name, "%-CrI by method and n-day forecast"))

save_plot(sharp_pl_wtitle, paste0("results/sharpness_q", qq_name, ".png"), w = 8, h = 8)
```


### Overestimation

```{r}
df_bias <- do.call(rbind, map(files, function(f) {
  print(sprintf("Processing file %s", f))
  read_files(f) %>% add_pred_score(f, models = models, type = "bias")
}))


bias_pl <- df_bias %>%
  summarize_score_by_n(fct = mean) %>%
  ggplot(aes(x = n, y = value, color = variable)) +
  geom_line() +
  geom_point(shape = 1) +
  geom_hline(aes(yintercept = 0.5), linetype = "dotted") +
  scale_x_continuous(minor_breaks = seq(0,21,1), expand = c(0,0), breaks = c(1,7,14,21), limits = c(0.5,21.5)) +
  scale_y_continuous(expand = c(0,0), limits = c(0.25, .75), breaks = seq(.25, .75, .25), labels = function(x) x * 100) +
  scale_color_manual(values = mcols) +
  labs(x = "Number of days forecasted ahead", 
       y = "Average overestimation (%)") +
  theme_bw2() +
  theme(legend.title = element_blank())

bias_pl

bias_pl_wtitle <- bias_pl +
  labs(title = "Bias",
       subtitle = "Overestimation by method and n-day forecast")

save_plot(bias_pl_wtitle, "results/bias.png", w = 8, h = 8)  
```

### Summary plot

```{r}
p1_descr <- mCalib_pl + labs(title = "a")
p2_descr <- pCalib_pl + theme(legend.position = "none") + labs(title = "b")
p3_descr <- sharp_pl + theme(legend.position = "none") + labs(title = "c")
p4_descr <- bias_pl + theme(legend.position = "none") + labs(title = "d")
csb_summary_pl <- grid.arrange(p1_descr, p2_descr, grid.arrange(p3_descr, p4_descr, ncol = 2), 
                               ncol = 1, widths = 16, heights = c(7, 5.5, 5.5))

save_plot(csb_summary_pl, "results/calibration-sharpness-bias.pdf", w = 16, h = 18)
```


## Performance

### CRPS

#### Overall

```{r}
df_cens_ps <- do.call(rbind, map(files, function(f) {
  print(sprintf("Processing file %s", f))
  read_files(f) %>% add_pred_score(f, models = models, type = "crps", trans = function(x) {x[x>max_inc] <- max_inc; return(x)})
}))

df_cens_ps_sum <- df_cens_ps %>%
  summarize_score_by_n(fct = mean) 

skill_pl <- df_cens_ps_sum %>%
  ggplot(aes(x = n, y = value, color = variable)) +
  geom_line() +
  geom_point(shape = 1) +
  scale_x_continuous(minor_breaks = seq(0,21,1), expand = c(0,0), breaks = c(1,7,14,21), limits = c(0.5,21.5)) +
  scale_y_continuous(expand = c(0,0), limits = c(0,35)) +
  scale_color_manual(values = mcols) +
  labs(x = "Number of days forecasted ahead", 
       y = "Average CRPS") +
  theme_bw2() +
  theme(legend.title = element_blank())
```

### ... by phase

```{r}
which_phase <- function(id, date) {
  date <- ifelse(date == "2021-03-15", as.Date("2021-03-14"), date)
  sub <- phase_labs %>%
    dplyr::filter(state == toupper(id)) %>%
    dplyr::filter(date >= start_date) %>%
    dplyr::filter(date < end_date)
  return(sub$epidemic_phase)
}
  
crps_by_phase <- df_cens_ps %>%
  rowwise() %>%
  mutate(phase = which_phase(state_id, date))

crps_by_phase_pl <- crps_by_phase %>%
  dplyr::select(c("n", "phase", models)) %>%
  melt(c("n", "phase")) %>%
  group_by(n, phase, variable) %>%
  summarize(value = mean(value)) %>%
  ungroup() %>%
  mutate(variable = recode(variable, !!! model_names)) %>%
  rbind(df_cens_ps_sum %>% mutate(phase = "total")) %>%
  mutate(phase = firstup(phase %>% as.character())) %>%
  mutate(phase = factor(phase, levels = c("Total", "Exponential growth", "Subexponential growth",
                                          "Plateau", "Subexponential decline", "Exponential decline"))) %>%
  ggplot(aes(x = n, y = value, color = variable)) +
  facet_wrap(~ phase) +
  geom_line() +
  geom_point(shape = 1) +
  scale_y_continuous(expand = c(0,0), limits = c(0, 60)) +
  scale_x_continuous(minor_breaks = seq(0,21,1), expand = c(0,0), breaks = c(1,7,14,21), limits = c(0.5,21.5)) +
  scale_color_manual(values = mcols) +
  labs(y = "Average CRPS", x = "Number of days forecasted ahead") +
  theme_bw2() +
  theme(legend.title = element_blank())

crps_by_phase_pl

crps_by_phase_pl_wtitle <- crps_by_phase_pl +
  labs(title = "Skill",
       subtitle = "Average continuous ranked probability score (CRPS) by model and epidemic phase")

save_plot(crps_by_phase_pl_wtitle, "results/skill.png", w = 16, h = 16)  
```


### ... by state 

```{r}
crps_by_state_pl <- df_cens_ps %>%
  dplyr::select(-incidence) %>%
  melt(c("state_id", "date", "n")) %>%
  group_by(variable, state_id, n) %>%
  summarize(value = mean(value)) %>%
  ungroup() %>%
  mutate(variable = recode(variable, !!! model_names)) %>%
  mutate(state_id = recode(state_id, !!! state_names)) %>%
  ggplot(aes(x = n, y = value, color = variable)) +
  facet_wrap(~ state_id) +
  geom_line() +
  geom_point(shape = 1) +
  scale_y_continuous(expand = c(0,0), limits = c(0, 60)) +
  scale_x_continuous(minor_breaks = seq(0,21,1), expand = c(0,0), breaks = c(1,7,14,21), limits = c(0.5,21.5)) +
  labs(y = "Average CRPS", x = "Number of days forecasted ahead") +
  theme_bw2() +
  theme(legend.title = element_blank())

crps_by_state_pl

save_plot(crps_by_state_pl, "results/skill_by_state.pdf", w = 16, h = 12)  
```

<!-- ```{r} -->
<!-- ### Weighting -->
<!-- WM <- data_delay(30, T, p_in, mu = rnorm(1e4, 10.92, 0.94), sigma = rnorm(1e4, 5.41, 0.27)) -->
<!-- w <- WM %>% -->
<!--   group_by(x) %>% -->
<!--   summarize(mean_weight = mean(value)) %>% -->
<!--   dplyr::select(mean_weight) %>% -->
<!--   unlist() -->

<!-- plot(w, xlab = "Days ahead", ylab = "Weight", type = "b") -->

<!-- df_ps_weighted <- df_cens_ps %>% -->
<!--   mutate_at(vars(models), ~ . * w[n]) %>% -->
<!--   group_by(state_id, date) %>% -->
<!--   summarize_at(vars(models), ~ sum(.)) %>% -->
<!--   ungroup() -->

<!-- crps_by_state_pl <- df_ps_weighted %>% -->
<!--   dplyr::select(-date) %>% -->
<!--   melt(c("state_id")) %>% -->
<!--   group_by(state_id, variable) %>% -->
<!--   summarize(value = mean(value)) %>% -->
<!--   ungroup() %>% -->
<!--   mutate(variable = recode(variable, !!! model_names)) %>% -->
<!--   mutate(state_id = recode(state_id, !!! state_names)) %>% -->
<!--   ggplot(aes(x = state_id, y = value, color = variable, group = variable)) + -->
<!--   geom_line() + -->
<!--   geom_point(shape = 1) + -->
<!--   scale_x_discrete(expand = c(0.05,0.05)) + -->
<!--   scale_color_manual(values = mcols) + -->
<!--   labs(y = "Weighted average CRPS") + -->
<!--   theme_bw2() + -->
<!--   theme(legend.title = element_blank(), axis.title.x = element_blank()) -->

<!-- crps_by_state_pl   -->

<!-- crps_by_state_pl_wtitle <- crps_by_state_pl + -->
<!--   labs(title = "Skill", -->
<!--        subtitle = "Weighted average CRPS by model and state") -->

<!-- save_plot(crps_by_state_pl_wtitle, "results/skill_by_state.png", w = 8, h = 8)   -->
<!-- ``` -->


<!-- ### CRPS -->

<!-- ```{r} -->
<!-- df_ps <- do.call(rbind, map(files, function(f) { -->
<!--   print(sprintf("Processing file %s", f)) -->
<!--   read_files(f) %>% add_pred_score(f, models = models, type = "crps") -->
<!-- })) -->

<!-- crps_pl <- df_ps %>% -->
<!--   plot_score(models = models, model_colors = mcols) + -->
<!--   labs(y = "Score", x = "Models", -->
<!--        title = "CRPS", -->
<!--        subtitle = "CRPS across states (AZ, CA, IL, MD, NJ, NY)") + -->
<!--   theme_bw2() -->

<!-- crps_pl -->
<!-- ``` -->

<!-- ### Censored -->

<!-- ```{r} -->
<!-- df_cens_ps <- do.call(rbind, map(files, function(f) { -->
<!--   print(sprintf("Processing file %s", f)) -->
<!--   read_files(f) %>% add_pred_score(f, models = models, type = "crps", trans = function(x) {x[x>max_inc] <- max_inc; return(x)}) -->
<!-- })) -->

<!-- cens_crps_pl <- df_cens_ps %>% -->
<!--   plot_score(models = models, model_colors = mcols) + -->
<!--   labs(y = "Score", x = "Models", -->
<!--        title = "Censored CRPS", -->
<!--        subtitle = "Censored CRPS across states (AZ, CA, IL, MD, NJ, NY)") + -->
<!--   theme_bw2() -->

<!-- cens_crps_pl -->
<!-- ``` -->

<!-- #### By N -->

<!-- ```{r} -->
<!-- crps_by_n_pl <- df_cens_ps %>% -->
<!--   dplyr::select(c("n", models)) %>% -->
<!--   melt(c("n")) %>% -->
<!--   group_by(n, variable) %>% -->
<!--   summarize(mean_score = mean(value)) %>% -->
<!--   ungroup() %>% -->
<!--   mutate(variable = factor(variable, levels = models)) %>% -->
<!--   ggplot(aes(x = n, y = mean_score, color = variable)) + -->
<!--   geom_line() + -->
<!--   geom_point() + -->
<!--   scale_y_continuous(expand = c(0,0), limits = c(0, NA)) + -->
<!--   scale_x_continuous(expand = c(0,0)) + -->
<!--   scale_color_manual(values = mcols) + -->
<!--   labs(y = "Score", x = "Number of days forecasted ahead", -->
<!--        title = "CRPS by n", -->
<!--        subtitle = "Average censored CRPS by n-day ahead forecast across states (AZ, CA, IL, MD, NJ, NY)") + -->
<!--   theme_bw2() -->

<!-- crps_by_n_pl -->

<!-- save_plot(crps_by_n_pl, "results/crps_by_n.png", w = 21, h = 14) -->
<!-- ``` -->

<!-- #### By phase -->

<!-- ```{r} -->
<!-- which_phase <- function(id, date) { -->
<!--   date <- ifelse(date == "2021-03-15", as.Date("2021-03-14"), date) -->
<!--   sub <- phase_labs %>% -->
<!--     dplyr::filter(state == toupper(id)) %>% -->
<!--     dplyr::filter(date >= start_date) %>% -->
<!--     dplyr::filter(date < end_date) -->
<!--   return(sub$epidemic_phase) -->
<!-- } -->

<!-- crps_by_phase <- df_cens_ps %>% -->
<!--   rowwise() %>% -->
<!--   mutate(phase = which_phase(state_id, date)) -->

<!-- crps_by_phase_pl <- crps_by_phase %>% -->
<!--   dplyr::select(c("n", "phase", models)) %>% -->
<!--   melt(c("n", "phase")) %>% -->
<!--   group_by(n, phase, variable) %>% -->
<!--   summarize(mean_score = mean(value)) %>% -->
<!--   ungroup() %>% -->
<!--   mutate(variable = factor(variable, levels = models)) %>% -->
<!--   ggplot(aes(x = n, y = mean_score, color = variable)) + -->
<!--   facet_wrap(~ phase) + -->
<!--   geom_line() + -->
<!--   geom_point() + -->
<!--   scale_y_continuous(expand = c(0,0), limits = c(0, NA)) + -->
<!--   scale_x_continuous(expand = c(0,0)) + -->
<!--   scale_color_manual(values = mcols) + -->
<!--   labs(y = "Score", x = "Number of days forecasted ahead", -->
<!--        title = "CRPS by epidemic phase", -->
<!--        subtitle = "Average censored CRPS by epidemic phase across states (AK, AL, AR, AZ, CA)") + -->
<!--   theme_bw2()  -->


<!-- crps_by_phase_pl -->

<!-- save_plot(crps_by_phase_pl, "results/crps_by_phase.png", w = 21, h = 14) -->
<!-- ``` -->

<!-- #### Till 1st peak -->

<!-- ```{r} -->
<!-- first_peak <- data.frame( -->
<!--   state_id = tolower(c("NY","NJ")), -->
<!--   date = as.Date(c("2020-04-07","2020-04-10")) -->
<!-- ) -->

<!-- crps_first_peak_pl <- df_cens_ps %>% -->
<!--   dplyr::filter((state_id == first_peak$state_id[1] & date <= first_peak$date[1]) |  -->
<!--                   (state_id == first_peak$state_id[2] & date <= first_peak$date[2]))  %>% -->
<!--   dplyr::select(c("n", models)) %>% -->
<!--   melt(c("n")) %>% -->
<!--   group_by(n, variable) %>% -->
<!--   summarize(mean_score = mean(value)) %>% -->
<!--   ungroup() %>% -->
<!--   mutate(variable = factor(variable, levels = models)) %>% -->
<!--   ggplot(aes(x = n, y = mean_score, color = variable)) + -->
<!--   geom_line() + -->
<!--   geom_point() + -->
<!--   scale_y_continuous(expand = c(0,0), limits = c(0, NA)) + -->
<!--   scale_x_continuous(expand = c(0,0)) + -->
<!--   scale_color_manual(values = mcols) + -->
<!--   labs(y = "Score", x = "Number of days forecasted ahead", -->
<!--        title = "CRPS until first peak", -->
<!--        subtitle = "Average censored CRPS until first peak across two states (NJ, NY)") + -->
<!--   theme_bw2()  -->

<!-- crps_first_peak_pl -->

<!-- save_plot(crps_first_peak_pl, "results/crps_until_first_peak.png", w = 10, h = 8) -->
<!-- ``` -->


<!-- ### Weighted -->

<!-- ```{r} -->
<!-- WM <- data_delay(30, T, p_in, mu = rnorm(1e4, 10.92, 0.94), sigma = rnorm(1e4, 5.41, 0.27)) -->
<!-- w <- WM %>% -->
<!--   group_by(x) %>% -->
<!--   summarize(mean_weight = mean(value)) %>% -->
<!--   dplyr::select(mean_weight) %>% -->
<!--   unlist() -->

<!-- plot(w, xlab = "Days ahead", ylab = "Weight", type = "b") -->

<!-- df_ps_weighted <- df_cens_ps %>% -->
<!--   mutate_at(vars(models), ~ . * w[n]) %>% -->
<!--   group_by(state_id, date) %>% -->
<!--   summarize_at(vars(models), ~ sum(.)) %>% -->
<!--   ungroup() -->

<!-- crps_weighted_pl <- df_ps_weighted %>% -->
<!--   plot_score(models = models, model_colors = mcols) + -->
<!--   theme_bw2() + -->
<!--   labs(y = "Score", x = "Model", -->
<!--        title = "Weighted censored CRPS", -->
<!--        subtitle = "Weighted censored CRPS across states (AK, AL, AR, AZ, CA)")  -->

<!-- crps_weighted_pl -->
<!-- ``` -->

<!-- ### Asymmetry  -->

<!-- ```{r} -->
<!-- bias_weight <- function(p) { -->
<!--   p <- p - 0.5 -->
<!--   if (p <= 0) { -->
<!--     (1 - p) ^ 2 -->
<!--   } else { -->
<!--     (1 + p) ^ 1 -->
<!--   } -->
<!-- } -->

<!-- plot(x = seq(0, 1, .01), y = 1 * sapply(seq(0, 1, .01), bias_weight), type = "b") -->

<!-- df_pb <- do.call(rbind, map(files, function(f) { -->
<!--   print(sprintf("Processing file %s", f)) -->
<!--   read_files(f) %>% add_pred_score(f, models = models, type = "bias") -->
<!-- })) -->

<!-- df_cens_ps_pb <- df_cens_ps -->
<!-- df_cens_ps_pb[ ,models] <- df_cens_ps_pb[ ,models] * apply(df_pb[ ,models], c(1,2), bias_weight) -->
<!-- df_cens_ps_pb_weighted <- df_cens_ps_pb %>% -->
<!--   mutate_at(vars(models), ~ . * w[n]) %>% -->
<!--   group_by(state_id, date) %>% -->
<!--   summarize_at(vars(models), ~ sum(.)) %>% -->
<!--   ungroup() -->

<!-- crps_asym_pl <- df_cens_ps_pb_weighted %>% -->
<!--   plot_score(models = models, model_colors = mcols) + -->
<!--   labs(y = "Score", x = "Model", -->
<!--        title = "Weighted asymmetric censored CRPS", -->
<!--        subtitle = "Weighted asymmetric censored CRPS across states (AK, AL, AR, AZ, CA)") + -->
<!--   theme_bw2() -->

<!-- crps_asym_pl -->
<!-- ``` -->

<!-- ```{r} -->
<!-- all_crps_pl <- grid.arrange(crps_pl, cens_crps_pl, crps_weighted_pl, crps_asym_pl, ncol = 2) -->
<!-- save_plot(all_crps_pl, "results/crps_comparison.png", w = 24, h = 18) -->
<!-- ``` -->

<!-- #### Over time -->

<!-- ```{r} -->
<!-- crps_over_time_pl <- df_cens_ps_pb_weighted %>% -->
<!--   mutate_at(vars(models), ~ zoo::rollmean(., k = 7, fill = NA, align = "center")) %>% -->
<!--   na.omit() %>% -->
<!--   melt(c("state_id", "date")) %>% -->
<!--   ggplot(aes(x = date, y = value, color = variable)) + -->
<!--   facet_wrap(~ state_id) + -->
<!--   geom_line() + -->
<!--   scale_x_date(expand = c(0,0)) + -->
<!--   labs(y = "Score", x = "Date", -->
<!--        title = "CRPS over time", -->
<!--        subtitle = "Weighted asymmetric censored CRPS over time by state and model") + -->
<!--   theme_bw2() + -->
<!--   theme(legend.title = element_blank()) -->

<!-- crps_over_time_pl -->

<!-- save_plot(crps_over_time_pl, "results/crps_over_time.png", w = 24, h = 18) -->
<!-- ``` -->


<!-- ## Regret -->

<!-- ```{r} -->
<!-- df_rr <- do.call(rbind, map(files, function(f) { -->
<!--   print(sprintf("Processing file %s", f)) -->
<!--   read_files(f) %>% -->
<!--     rowwise() %>% -->
<!--     mutate_at(vars(models), ~ regret_score(., new_confirmed, pop = population[1], w = w, b = .5)) %>% -->
<!--     unnest(cols = c("n", "date", "new_confirmed", models)) -->
<!-- })) -->
<!-- ``` -->

<!-- ### Overall -->

<!-- ```{r} -->
<!-- regret_pl <- df_rr %>% -->
<!--   dplyr::select(id, models) %>% -->
<!--   reshape2::melt(c("id")) %>% -->
<!--   group_by(variable) %>% -->
<!--   summarize(m = median(value), -->
<!--             q1 = quantile(value, .25), -->
<!--             q3 = quantile(value, .75)) %>% -->
<!--   ungroup() %>% -->
<!--   ggplot(aes(x = variable)) + -->
<!--   geom_point(aes(y = m)) + -->
<!--   geom_errorbar(aes(ymin = q1, ymax = q3), width = .1) + -->
<!--   theme_bw2() + -->
<!--   theme(axis.title.x = element_blank()) + -->
<!--   labs(y = "Regret score (Median and IQR)", x = "", -->
<!--        title = "Regret", -->
<!--        subtitle = "Regret score by method and length of forecast") + -->
<!--   theme_bw2() -->

<!-- regret_pl -->

<!-- save_plot(regret_pl, "results/regret.pdf", w = 21, h = 14) -->
<!-- ``` -->

<!-- ### By ID -->

<!-- ```{r} -->
<!-- regret_by_id_pl <- df_rr %>% -->
<!--   dplyr::select(id, models) %>% -->
<!--   reshape2::melt(c("id")) %>% -->
<!--   group_by(id, variable) %>% -->
<!--   summarize(m = median(value)) %>% -->
<!--   ungroup() %>% -->
<!--   ggplot(aes(x = id, y = m, fill = variable)) + -->
<!--   geom_bar(stat = "identity", position = position_dodge()) + -->
<!--   scale_fill_manual(values = mcols) + -->
<!--   theme_bw2() + -->
<!--   theme(axis.title.x = element_blank(), legend.title = element_blank()) + -->
<!--   labs(y = "Regret score (Median)", x = "", -->
<!--        title = "Regret", -->
<!--        subtitle = "Regret score by method and country")  -->

<!-- regret_by_id_pl -->

<!-- save_plot(regret_by_id_pl, "results/regret_by_id.pdf", w = 21, h = 14) -->
<!-- ``` -->


<!-- ### By incidence -->

<!-- ```{r} -->
<!-- regret_by_inc_pl <- df_rr %>% -->
<!--   mutate(incidence = trans(new_confirmed, pop = population, transfct = NULL)) %>% -->
<!--   mutate(group = cut(incidence, breaks = c(-Inf, 30, 50, 100, Inf),  -->
<!--                      labels = paste(c("low", "medium", "high", "very high"), "incidence", sep = " "))) %>% -->
<!--   dplyr::select(id, group, models) %>% -->
<!--   reshape2::melt(c("id", "group")) %>% -->
<!--   plot_score() + -->
<!--   labs(y = "CRPS (Median and IQR)", x = "", -->
<!--        title = "Skill", -->
<!--        subtitle = "CRPS by method and incidence") + -->
<!--   theme_bw2() -->

<!-- regret_by_inc_pl -->

<!-- save_plot(regret_by_inc_pl, "results/regret_by_inc.pdf", w = 21, h = 14) -->
<!-- ``` -->

### Hotspot prediction

```{r}
# compute probabilities for hotspot
df_hot <- do.call(rbind, map(files, function(f) {
  # read file
  print(sprintf("Processing file %s", f))
  df <- read_files(f) %>%
    dplyr::filter(sapply(data, nrow) == 21)
  
  # compute hotspot probabilities and create list from matrix
  prob_hot <- lapply(models, function(m) {
    P <- sapply(df$data, function(X) p_hotspot(X[[m]])) 
    lapply(seq_len(ncol(P)), function(i) P[ ,i]) })
  names(prob_hot) <- models
  
  # determine true (if hotspot) and create list from matrix
  hot <- sapply(df$data, function(X) is_hotspot(X$incidence))
  prob_hot$hot <- lapply(seq_len(ncol(hot)), function(i) hot[ ,i])
  
  # add state_id and n to list
  prob_hot$n <- lapply(1:length(df$data), function(x) 1:nrow(hot) + 7)
  prob_hot$state_id <- tolower(gsub(".rds", "", basename(f)))
  prob_hot$date <- df$forecast_date
  
  # combine to long dataframe
  prob_hot <- unnest(as_data_frame(prob_hot), c("n", "hot", "date", models)) 
}))

# proportion of hotspots
df_prop <- df_hot %>%
  #dplyr::filter(!is.na(hot)) %>%
  group_by(state_id, date) %>%
  slice(1) %>%
  ungroup()

sum(df_prop$hot==1, na.rm = T) / nrow(df_prop)
```

#### AUC

```{r}
df_hot_pl <- df_hot %>%
  filter(!is.na(hot)) %>%
  melt(c("n", "hot", "state_id", "date")) %>%
  group_by(n, variable) %>%
  summarize(AUC = auc(hot, value)[1]) %>%
  ungroup() %>%
  mutate(variable = recode(variable, !!! model_names)) %>%
  ggplot(aes(x = n, y = AUC, color = variable)) +
  geom_point(shape = 1) +
  geom_line() +
  geom_hline(aes(yintercept = 0.5), linetype = "dashed") +
  scale_color_manual(values = mcols) +
  scale_x_continuous(minor_breaks = seq(0,21,1), expand = c(0,0), breaks = c(8,14,21), limits = c(7.5,21.5)) +
  scale_y_continuous(breaks = seq(0.4, 0.8, .1), labels = function(x) x * 100) +
  labs(x = "Number of days forecasted ahead", 
       y = "AUC (%)") +
  theme_bw2() +
  theme(legend.title = element_blank()) 
  
df_hot_pl

df_hot_pl_wtitle <- df_hot_pl +
  labs(title = "Hotspot",
       subtitle = "AUC for hotspot pred. by model and n-day forecast")

save_plot(df_hot_pl_wtitle, "results/hotspot.png", w = 8, h = 8)
```

#### Sensitivity

```{r}
sensitivity.topleft <- function(obs, pred) {
  c(coords(roc(obs,pred), best.method="topleft", x="best")["sensitivity"])
} 

df_hot_sens_pl <- df_hot %>%
  filter(!is.na(hot)) %>%
  melt(c("n", "hot", "state_id", "date")) %>%
  group_by(n, variable) %>%
  summarize(sens = unlist(sensitivity.topleft(hot, value))) %>%
  ungroup() %>%
  mutate(variable = recode(variable, !!! model_names)) %>%
  ggplot(aes(x = n, y = sens, color = variable)) +
  geom_point(shape = 1) +
  geom_line() +
  geom_hline(aes(yintercept = 0.5), linetype = "dashed") +
  scale_color_manual(values = mcols) +
  scale_x_continuous(minor_breaks = seq(0,21,1), expand = c(0,0), breaks = c(8,14,21), limits = c(7.5,21.5)) +
  scale_y_continuous(breaks = seq(0.4, 0.8, .1), labels = function(x) x * 100) +
  labs(x = "Number of days forecasted ahead", 
       y = "Sensitivity (%)") +
  theme_bw2() +
  theme(legend.title = element_blank()) 
  
df_hot_sens_pl
```

#### Specificity

```{r}
specificity.topleft <- function(obs, pred) {
  c(coords(roc(obs,pred), best.method="topleft", x="best")["specificity"])
} 

df_hot_spec_pl <- df_hot %>%
  filter(!is.na(hot)) %>%
  melt(c("n", "hot", "state_id", "date")) %>%
  group_by(n, variable) %>%
  summarize(sens = unlist(specificity.topleft(hot, value))) %>%
  ungroup() %>%
  mutate(variable = recode(variable, !!! model_names)) %>%
  ggplot(aes(x = n, y = sens, color = variable)) +
  geom_point(shape = 1) +
  geom_line() +
  geom_hline(aes(yintercept = 0.5), linetype = "dashed") +
  scale_color_manual(values = mcols) +
  scale_x_continuous(minor_breaks = seq(0,21,1), expand = c(0,0), breaks = c(8,14,21), limits = c(7.5,21.5)) +
  scale_y_continuous(breaks = seq(0.4, 0.8, .1), labels = function(x) x * 100) +
  labs(x = "Number of days forecasted ahead", 
       y = "Specificity (%)") +
  theme_bw2() +
  theme(legend.title = element_blank()) 
  
df_hot_spec_pl
```

### Summary plot

```{r}
perf_sum_pl <- grid.arrange(crps_by_phase_pl + labs(title = "a"), 
                            grid.arrange(df_hot_pl + theme(legend.position = "none") + labs(title = "b"),
                                         df_hot_sens_pl + theme(legend.position = "none") + labs(title = " "), 
                                         df_hot_spec_pl + theme(legend.position = "none") + labs(title = " "),
                                         ncol = 3),
                            ncol = 1, widths = 16, heights = c(12, 6))

save_plot(perf_sum_pl, "results/performance.pdf", w = 16, h = 18)
```

<!-- ### TPP and FPP -->

<!-- ```{r} -->
<!-- df_crit <- do.call(rbind, map(files[1], function(f) { -->
<!--   print(sprintf("Processing file %s", f)) -->
<!--   read_files(f) %>% -->
<!--     dplyr::select(id, new_confirmed, date, n, arima, prophet, cori, population) %>% -->
<!--     rowwise() %>% -->
<!--     mutate_at(vars(arima, cori, prophet), list(Q25 = ~ pred_score(. / population * 1e5, type = "critical", q = 25))) %>% -->
<!--     mutate_at(vars(arima, cori, prophet), list(Q50 = ~ pred_score(./ population * 1e5, type = "critical", q = 50))) %>% -->
<!--     mutate_at(vars(arima, cori, prophet), list(Q75 = ~ pred_score(. / population * 1e5, type = "critical", q = 75))) %>% -->
<!--     mutate_at(vars(arima, cori, prophet), list(Q100 = ~ pred_score(. / population * 1e5, type = "critical", q = 100))) %>% -->
<!--     dplyr::select(-arima, -cori, -prophet) %>% -->
<!--     unnest(cols = c("n", "date", "new_confirmed",  -->
<!--                     "arima_Q25", "cori_Q25", "prophet_Q25", "arima_Q50", "cori_Q50", "prophet_Q50", -->
<!--                     "arima_Q75", "cori_Q75", "prophet_Q75", "arima_Q100", "cori_Q100", "prophet_Q100")) -->
<!-- })) -->

<!-- df_crit_weight <- df_crit %>% -->
<!--   reshape2::melt(c("n", "id", "date", "new_confirmed", "population")) %>% -->
<!--   mutate(threshold = as.numeric(stringi::stri_extract(variable, regex = "\\d{2,3}"))) %>% -->
<!--   mutate(variable = gsub("_Q\\d{2,3}", "", variable)) %>% -->
<!--   mutate(value = value * w[n]) %>% -->
<!--   group_by(id, date, threshold, variable, new_confirmed, population) %>% -->
<!--   summarize(value = sum(value)) %>% -->
<!--   ungroup() -->

<!-- # subset critical values -->
<!-- df_crit_weight_sub <- df_crit_weight %>% -->
<!--   group_by(id, variable, threshold) %>% -->
<!--   arrange(date) %>% -->
<!--   mutate(is_crit = is_critical(new_confirmed / population * 1e5, threshold[1], min_x = 10)) %>% -->
<!--   ungroup() %>% -->
<!--   dplyr::filter(!is.na(is_crit)) -->

<!-- weighted_tpp_pl <- df_crit_weight_sub %>% -->
<!--   dplyr::filter(is_crit == "up") %>% -->
<!--   rename(group = threshold) %>% -->
<!--   plot_score() + -->
<!--   scale_x_continuous(limits = c(0, 1), expand = c(0,0), labels = function(x) x * 100) + -->
<!--   labs(x = "Weighted true positive probability (TPP)",  -->
<!--        y = "Method", -->
<!--        title = "Critical Incidence", -->
<!--        subtitle = "Weighted TPP by critical incidence") + -->
<!--   theme_bw2() -->

<!-- weighted_tpp_pl -->


<!-- weighted_fpp_pl <- df_crit_weight_sub %>% -->
<!--   dplyr::filter(is_crit == "down") %>% -->
<!--   rename(group = threshold) %>% -->
<!--   plot_score() + -->
<!--   scale_x_continuous(limits = c(0, 1), expand = c(0,0), labels = function(x) x * 100) + -->
<!--   labs(x = "Weighted false positive probability (%)",  -->
<!--        y = "Method", -->
<!--        title = "Critical incidence", -->
<!--        subtitle = "Weighted FPP by critical incidence") + -->
<!--   theme_bw2() -->

<!-- weighted_fpp_pl -->

<!-- df_crit_weight_f1 <- df_crit_weight_sub %>% -->
<!--   group_by(id, variable, is_crit, threshold) %>% -->
<!--   summarize(value = mean(value)) %>% -->
<!--   reshape2::dcast(id + variable + threshold ~ is_crit) %>% -->
<!--   mutate(f1 = up / (up + 0.5 * (down + (1-up)))) -->

<!-- weighted_f1_pl <- df_crit_weight_f1 %>% -->
<!--   rename(group = threshold, value = f1) %>% -->
<!--   plot_score() + -->
<!--   scale_x_continuous(limits = c(0, 1), expand = c(0,0), labels = function(x) x * 100) + -->
<!--   labs(x = "F1 (%)",  -->
<!--        y = "Method", -->
<!--        title = "Critical incidence", -->
<!--        subtitle = "Weighted F1-score by critical incidence", -->
<!--        caption = "Note: TPP and FPP are summarized by ID and then F1 is computed.") + -->
<!--   theme_bw2() -->

<!-- weighted_f1_pl -->

<!-- critical_pl <- arrangeGrob(weighted_tpp_pl, weighted_fpp_pl, weighted_f1_pl, ncol = 2) -->

<!-- save_plot(critical_pl, "results/critical_incidence.pdf", w = 21, h = 18) -->
<!-- ``` -->

<!-- ## Peak delay -->

<!-- ```{r} -->
<!-- df_peak <- do.call(rbind, map(files, function(f) { -->
<!--   print(sprintf("Processing file %s", f)) -->
<!--   df <- read_files(f) %>% -->
<!--     dplyr::select(id, population, new_confirmed, date, n, arima, prophet, cori) %>% -->
<!--     rowwise() %>% -->
<!--     mutate_at(vars(arima, cori, prophet), ~ list(apply(., 1, mean))) %>% -->
<!--     unnest(cols = c("n", "date", "new_confirmed", "arima", "cori", "prophet")) %>% -->
<!--     mutate_at(vars(new_confirmed, arima, cori, prophet), ~ . / population * 1e5) %>% -->
<!--     dplyr::select(id, date, n, new_confirmed, arima, cori, prophet)  -->

<!--   df %>% -->
<!--     group_by(id, n) %>% -->
<!--     nest() %>% -->
<!--     mutate(data = map(data, ~ mutate(.x, peak = is_peak(new_confirmed, min_x = 15)))) %>% -->
<!--     mutate(data = map(data, ~ mutate_at(.x, vars(arima, cori, prophet), list(peak = ~ is_closest_peak(., peak, t_right = Inf))))) %>% -->
<!--     mutate(data_peak = map(data, function(D) { -->
<!--       pd <- data.frame(cbind.fill( -->
<!--         (D$date[D$peak]), -->
<!--         (D$date[D$arima_peak]), -->
<!--         (D$date[D$cori_peak]), -->
<!--         (D$date[D$prophet_peak]), -->
<!--         (D$new_confirmed[D$peak]), -->
<!--         (D$arima[D$arima_peak]), -->
<!--         (D$cori[D$cori_peak]), -->
<!--         (D$prophet[D$prophet_peak]) -->
<!--       ), stringsAsFactors = F) %>% -->
<!--         set_names(c("obs_date", "arima_date", "cori_date", "prophet_date", -->
<!--                     "obs_inc", "arima_inc", "cori_inc", "prophet_inc")) %>% -->
<!--         mutate_at(vars(matches("date")), as.Date, origin = "1970-01-01") %>% -->
<!--         mutate_at(vars(matches("inc")), as.numeric) -->
<!--       return(pd) -->
<!--     })) %>% -->
<!--     dplyr::select(id, n, data_peak) %>% -->
<!--     unnest(cols = "data_peak") %>% -->
<!--     group_by(id, n) %>% -->
<!--     mutate(peak_no = 1:n()) %>% -->
<!--     ungroup() -->
<!-- })) -->

<!-- # nuber of peaks by country -->
<!-- df_peak %>%  -->
<!--   group_by(id) %>% -->
<!--   summarize(max(peak_no))  -->

<!-- peak_delay <- df_peak %>% -->
<!--   group_by(id) %>% -->
<!--   dplyr::filter(obs_inc == max(obs_inc)) %>% # use maximum peak for now -->
<!--   mutate_at(vars(arima_date, cori_date, prophet_date), list(ddiff = ~ n - as.numeric(. - obs_date)))  -->

<!-- peak_delay_pl <- peak_delay %>% -->
<!--   mutate(n = cut(n, breaks = n_brks, labels = n_lbs)) %>% -->
<!--   dplyr::select(id, n, matches("ddiff")) %>% -->
<!--   melt(c("id", "n")) %>% -->
<!--   mutate(variable = gsub("_date_ddiff", "", variable)) %>% -->
<!--   rename(group = n) %>% -->
<!--   plot_score(CrI = c(0.5, 0.8)) + -->
<!--   geom_vline(aes(xintercept = 0), linetype = "dotted") + -->
<!--   labs(x = "Predicted days ahead - (method peak - observed peak)",  -->
<!--        y = "Method", -->
<!--        title = "Peak delay", -->
<!--        subtitle = "Peak delay by method and weekly ahead forecast", -->
<!--        caption = "Note: Data summarized by the highest peak of each country.") + -->
<!--   theme_bw2() -->

<!-- save_plot(peak_delay_pl, "results/peak_delay.pdf", w = 21, h = 18) -->
<!-- ``` -->





