---
title: "Experiments"
author: "Nicolas Banholzer"
date: '2022-04-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}
# libraries
library(tidyverse)
library(reshape2)
library(lubridate)
library(grid)
library(gridExtra)
library(covidcast)
library(RColorBrewer)

# utils
source("utils/eval.r")
source("utils/delays.r")

# helper
source("helper/plotting.r")

# settings
max_inc = 300
```

## Cori

### Data

```{r}
files_cori <- list.files("predictions/experiment_cori/", full.names = T)
models_cori = c("cori7", "cori14", "cori21")
```

### Results

```{r}
# compute scores
scores_cori <- do.call(rbind, map(files_cori, function(f) {
  print(sprintf("Processing file %s", f))
  read_files(f) %>% add_pred_score(f, models = models_cori, 
                                   type = "crps", trans = function(x) {x[x>max_inc] <- max_inc; return(x)})
}))

# summarize scores
scores_cori_sum <- scores_cori %>%
  dplyr::select(n, models_cori) %>%
  melt("n") %>%
  group_by(n, variable) %>%
  summarize(value = mean(value)) %>%
  ungroup()

# plot 
cori_pl <- scores_cori_sum %>%
  ggplot(aes(x = n, y = value, color = variable)) +
  geom_line() +
  geom_point(shape = 1) +
  scale_x_continuous(minor_breaks = seq(0,21,1), expand = c(0,0), breaks = c(1,7,14,21), limits = c(0.5,21.5)) +
  scale_y_continuous(expand = c(0,0), limits = c(0,35)) +
  scale_color_manual(values = brewer.pal(9,"Greens")[rev(c(3,6,9))],
                     labels = expression("EpiEstim("*tau*" = "*1*" week)","EpiEstim("*tau*" = "*2*" weeks)","EpiEstim("*tau*" = "*3*" weeks)")) +
  labs(x = "Number of days forecasted ahead", 
       y = "Average CRPS") +
  theme_bw2() +
  theme(legend.title = element_blank())

save_plot(cori_pl, "results/experiments_cori.pdf", w = 12, h = 8)
```


## Prophet

### Data

```{r}
files_proph <- list.files("predictions/experiment_prophet/", full.names = T)
models_proph = c("proph0.10", "proph0.25", "proph0.40")
```

### Results

```{r}
# compute scores
scores_proph <- do.call(rbind, map(files_proph, function(f) {
  print(sprintf("Processing file %s", f))
  read_files(f) %>% add_pred_score(f, models = models_proph, 
                                   type = "crps", trans = function(x) {x[x>max_inc] <- max_inc; return(x)})
}))

# summarize scores
scores_proph_sum <- scores_proph %>%
  dplyr::select(n, models_proph) %>%
  melt("n") %>%
  group_by(n, variable) %>%
  summarize(value = mean(value)) %>%
  ungroup()

# plot 
prophet_pl <- scores_proph_sum %>%
  ggplot(aes(x = n, y = value, color = variable)) +
  geom_line() +
  geom_point(shape = 1) +
  scale_x_continuous(minor_breaks = seq(0,21,1), expand = c(0,0), breaks = c(1,7,14,21), limits = c(0.5,21.5)) +
  scale_y_continuous(expand = c(0,0), limits = c(0,35)) +
  scale_color_manual(values = brewer.pal(9,"Purples")[rev(c(3,6,9))],
                     labels = expression("Prophet("*tau*" = "*0.10*")","Prophet("*tau*" = "*0.25*")","Prophet("*tau*" = "*0.40*")")) +
  labs(x = "Number of days forecasted ahead", 
       y = "Average CRPS") +
  theme_bw2() +
  theme(legend.title = element_blank())

# zoom in on Prophet(0.10) and Prophet(0.25)
prophet_pl_zoom <- scores_proph_sum %>%
  dplyr::filter(variable != "proph0.10") %>%
  spread(variable, value) %>%
  mutate(dp = proph0.25 - proph0.40) %>%
  ggplot(aes(x = n, y = dp)) +
  geom_hline(aes(yintercept = 0), linetype = "dashed") +
  geom_line() +
  geom_point() +
  scale_x_continuous(minor_breaks = seq(0,21,1), expand = c(0,0), breaks = c(1,7,14,21), limits = c(0.5,21.5)) +
  #scale_y_continuous(expand = c(0.005,0.005)) +
  labs(x = "Number of days forecasted ahead", 
       y = "Difference in average CRPS\nbetween Prophet(0.25) and Prophet(0.10)") +
  theme_bw2() +
  theme(legend.title = element_blank())

# combine into one plot
proph_pl <- grid.arrange(prophet_pl + labs(title = "a"), prophet_pl_zoom + labs(title = "b"),
                         ncol = 1, widths = 12, heights = c(8,8))

save_plot(proph_pl, "results/experiments_proph.pdf", w = 12, h = 16)
```
